runtime: python39
entrypoint: gunicorn -b :$PORT web:app
instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 15
  target_throughput_utilization: 0.6

env_variables:
  PORT: "8080"

handlers:
  - url: /_pycache_
    static_dir: _pycache_

  - url: /(.*\.(html|css|js|png|jpg|pyc|txt))
    static_files: \1
    upload: /(.*\.(html|css|js|png|jpg|pyc|txt))

  - url: /.*
    static_files: index.html
    upload: index.html